[package]
name = "xhook-rs"
version = "0.1.0"
authors = ["wuhx <i@xun.im>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xhook-sys = { path = "xhook-sys"}
libc = "0.2"

[workspace]
members = [
    "xhook-sys",
]
