[package]
name = "xhook-sys"
version = "0.1.0"
authors = ["wuhx <i@xun.im>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.54"

[dependencies]
libc = "0.2"
